# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := native-activity
LOCAL_SRC_FILES := main.c \
	irrlicht/CParticleGravityAffector.cpp \
	irrlicht/CTRTextureFlat.cpp \
	irrlicht/CParticleSphereEmitter.cpp \
	irrlicht/CCameraSceneNode.cpp \
	irrlicht/CZipReader.cpp \
	irrlicht/COgreMeshFileLoader.cpp \
	irrlicht/COGLES2SLMaterialRenderer.cpp \
	irrlicht/CTRTextureBlend.cpp \
	irrlicht/CTRTextureLightMap2_M1.cpp \
	irrlicht/CZBuffer.cpp \
	irrlicht/COGLES2Driver.cpp \
	irrlicht/CShadowVolumeSceneNode.cpp \
	irrlicht/CImageLoaderTGA.cpp \
	irrlicht/CGUIEditBox.cpp \
	irrlicht/CTRTextureFlatWire.cpp \
	irrlicht/CMeshManipulator.cpp \
	irrlicht/CSceneNodeAnimatorFlyStraight.cpp \
	irrlicht/CSkyBoxSceneNode.cpp \
	irrlicht/CTRTextureGouraudWire.cpp \
	irrlicht/COGLES2Texture.cpp \
	irrlicht/CIrrDeviceConsole.cpp \
	irrlicht/CImageWriterPSD.cpp \
	irrlicht/CDefaultSceneNodeFactory.cpp \
	irrlicht/CGUIModalScreen.cpp \
	irrlicht/CFPSCounter.cpp \
	irrlicht/CSoftwareTexture.cpp \
	irrlicht/CSceneNodeAnimatorCameraMaya.cpp \
	irrlicht/CD3D9HLSLMaterialRenderer.cpp \
	irrlicht/CTRGouraudWire.cpp \
	irrlicht/CSoftwareDriver2.cpp \
	irrlicht/CTRTextureLightMap2_Add.cpp \
	irrlicht/CTRTextureLightMap2_M2.cpp \
	irrlicht/CSceneLoaderIrr.cpp \
	irrlicht/CGUIInOutFader.cpp \
	irrlicht/CGUIMessageBox.cpp \
	irrlicht/CGUIFont.cpp \
	irrlicht/CAnimatedMeshSceneNode.cpp \
	irrlicht/CPLYMeshWriter.cpp \
	irrlicht/CImageWriterPNG.cpp \
	irrlicht/CSceneNodeAnimatorFlyCircle.cpp \
	irrlicht/COpenGLSLMaterialRenderer.cpp \
	irrlicht/CAnimatedMeshMD3.cpp \
	irrlicht/CNullDriver.cpp \
	irrlicht/CGUIColorSelectDialog.cpp \
	irrlicht/lzma/LzmaDec.c \
	irrlicht/CCubeSceneNode.cpp \
	irrlicht/CDefaultGUIElementFactory.cpp \
	irrlicht/CCSMLoader.cpp \
	irrlicht/CGUIWindow.cpp \
	irrlicht/COGLES2Renderer2D.cpp \
	irrlicht/CTriangleBBSelector.cpp \
	irrlicht/COctreeSceneNode.cpp \
	irrlicht/CGUISpriteBank.cpp \
	irrlicht/CTRGouraudAlphaNoZ2.cpp \
	irrlicht/CMetaTriangleSelector.cpp \
	irrlicht/CPakReader.cpp \
	irrlicht/CImageLoaderJPG.cpp \
	irrlicht/CWADReader.cpp \
	irrlicht/CGUITabControl.cpp \
	irrlicht/CGUITable.cpp \
	irrlicht/CLWOMeshFileLoader.cpp \
	irrlicht/CEmptySceneNode.cpp \
	irrlicht/CTRTextureGouraudAlphaNoZ.cpp \
	irrlicht/COGLESExtensionHandler.cpp \
	irrlicht/CTRTextureWire2.cpp \
	irrlicht/CSceneNodeAnimatorTexture.cpp \
	irrlicht/CReadFile.cpp \
	irrlicht/CGUITreeView.cpp \
	irrlicht/CDMFLoader.cpp \
	irrlicht/CSphereSceneNode.cpp \
	irrlicht/CAnimatedMeshMD2.cpp \
	irrlicht/CImageWriterTGA.cpp \
	irrlicht/libpng/pngrtran.c \
	irrlicht/libpng/pngrio.c \
	irrlicht/libpng/pngwio.c \
	irrlicht/libpng/pngwrite.c \
	irrlicht/libpng/example.c \
	irrlicht/libpng/pngtrans.c \
	irrlicht/libpng/pngpread.c \
	irrlicht/libpng/pngset.c \
	irrlicht/libpng/pngwutil.c \
	irrlicht/libpng/pngmem.c \
	irrlicht/libpng/pngget.c \
	irrlicht/libpng/pngread.c \
	irrlicht/libpng/pngwtran.c \
	irrlicht/libpng/pngrutil.c \
	irrlicht/libpng/png.c \
	irrlicht/libpng/pngerror.c \
	irrlicht/CTarReader.cpp \
	irrlicht/CGUIMenu.cpp \
	irrlicht/COGLES2ExtensionHandler.cpp \
	irrlicht/CIrrDeviceStub.cpp \
	irrlicht/CIrrDeviceIPhone.cpp \
	irrlicht/CAttributes.cpp \
	irrlicht/jpeglib/jcarith.c \
	irrlicht/jpeglib/rdcolmap.c \
	irrlicht/jpeglib/jfdctflt.c \
	irrlicht/jpeglib/jdapimin.c \
	irrlicht/jpeglib/rdppm.c \
	irrlicht/jpeglib/wrgif.c \
	irrlicht/jpeglib/jdcolor.c \
	irrlicht/jpeglib/jerror.c \
	irrlicht/jpeglib/jquant1.c \
	irrlicht/jpeglib/rdbmp.c \
	irrlicht/jpeglib/jaricom.c \
	irrlicht/jpeglib/jcmaster.c \
	irrlicht/jpeglib/jcinit.c \
	irrlicht/jpeglib/jdapistd.c \
	irrlicht/jpeglib/jdsample.c \
	irrlicht/jpeglib/jfdctfst.c \
	irrlicht/jpeglib/jdinput.c \
	irrlicht/jpeglib/jcapistd.c \
	irrlicht/jpeglib/jidctfst.c \
	irrlicht/jpeglib/jdatasrc.c \
	irrlicht/jpeglib/rdgif.c \
	irrlicht/jpeglib/jddctmgr.c \
	irrlicht/jpeglib/transupp.c \
	irrlicht/jpeglib/jutils.c \
	irrlicht/jpeglib/wrtarga.c \
	irrlicht/jpeglib/jmemnobs.c \
	irrlicht/jpeglib/jmemmgr.c \
	irrlicht/jpeglib/rdtarga.c \
	irrlicht/jpeglib/jdmerge.c \
	irrlicht/jpeglib/rdrle.c \
	irrlicht/jpeglib/jcapimin.c \
	irrlicht/jpeglib/jcdctmgr.c \
	irrlicht/jpeglib/jchuff.c \
	irrlicht/jpeglib/jdmaster.c \
	irrlicht/jpeglib/jdmarker.c \
	irrlicht/jpeglib/jctrans.c \
	irrlicht/jpeglib/jdcoefct.c \
	irrlicht/jpeglib/wrppm.c \
	irrlicht/jpeglib/jcomapi.c \
	irrlicht/jpeglib/jfdctint.c \
	irrlicht/jpeglib/rdswitch.c \
	irrlicht/jpeglib/jcsample.c \
	irrlicht/jpeglib/jdhuff.c \
	irrlicht/jpeglib/jdmainct.c \
	irrlicht/jpeglib/wrrle.c \
	irrlicht/jpeglib/jcparam.c \
	irrlicht/jpeglib/jconfig.cfg \
	irrlicht/jpeglib/jquant2.c \
	irrlicht/jpeglib/jcmarker.c \
	irrlicht/jpeglib/jccoefct.c \
	irrlicht/jpeglib/jdarith.c \
	irrlicht/jpeglib/wrbmp.c \
	irrlicht/jpeglib/jdatadst.c \
	irrlicht/jpeglib/jidctflt.c \
	irrlicht/jpeglib/jdpostct.c \
	irrlicht/jpeglib/jcprepct.c \
	irrlicht/jpeglib/jdtrans.c \
	irrlicht/jpeglib/jidctint.c \
	irrlicht/jpeglib/jcmainct.c \
	irrlicht/jpeglib/jccolor.c \
	irrlicht/CTRTextureGouraudAddNoZ2.cpp \
	irrlicht/CImageLoaderRGB.cpp \
	irrlicht/CTerrainTriangleSelector.cpp \
	irrlicht/CNPKReader.cpp \
	irrlicht/CB3DMeshFileLoader.cpp \
	irrlicht/CBSPMeshFileLoader.cpp \
	irrlicht/Irrlicht.cpp \
	irrlicht/COctreeTriangleSelector.cpp \
	irrlicht/CGUIImage.cpp \
	irrlicht/COBJMeshWriter.cpp \
	irrlicht/CWriteFile.cpp \
	irrlicht/CTRTextureLightMap2_M4.cpp \
	irrlicht/CImageWriterPPM.cpp \
	irrlicht/CTRTextureGouraudAdd.cpp \
	irrlicht/CImageWriterJPG.cpp \
	irrlicht/CTerrainSceneNode.cpp \
	irrlicht/CGUIListBox.cpp \
	irrlicht/CIrrDeviceWinCE.cpp \
	irrlicht/CXMeshFileLoader.cpp \
	irrlicht/CTRTextureGouraudAlpha.cpp \
	irrlicht/CD3D8Driver.cpp \
	irrlicht/CD3D8ShaderMaterialRenderer.cpp \
	irrlicht/C3DSMeshFileLoader.cpp \
	irrlicht/CBurningShader_Raster_Reference.cpp \
	irrlicht/COGLES2NormalMapRenderer.cpp \
	irrlicht/CVolumeLightSceneNode.cpp \
	irrlicht/CSceneNodeAnimatorFollowSpline.cpp \
	irrlicht/CTRGouraud2.cpp \
	irrlicht/CGUISkin.cpp \
	irrlicht/CTriangleSelector.cpp \
	irrlicht/COpenGLParallaxMapRenderer.cpp \
	irrlicht/CLightSceneNode.cpp \
	irrlicht/COpenGLTexture.cpp \
	irrlicht/CGUIStaticText.cpp \
	irrlicht/CImageLoaderPNG.cpp \
	irrlicht/CImageWriterBMP.cpp \
	irrlicht/CGUIMeshViewer.cpp \
	irrlicht/CMeshSceneNode.cpp \
	irrlicht/CGUIImageList.cpp \
	irrlicht/CPLYMeshFileLoader.cpp \
	irrlicht/CWaterSurfaceSceneNode.cpp \
	irrlicht/CSoftwareDriver.cpp \
	irrlicht/CTRStencilShadow.cpp \
	irrlicht/CTRGouraud.cpp \
	irrlicht/CGeometryCreator.cpp \
	irrlicht/CParticleScaleAffector.cpp \
	irrlicht/CMD3MeshFileLoader.cpp \
	irrlicht/CColladaFileLoader.cpp \
	irrlicht/aesGladman/aeskey.cpp \
	irrlicht/aesGladman/aescrypt.cpp \
	irrlicht/aesGladman/prng.cpp \
	irrlicht/aesGladman/pwd2key.cpp \
	irrlicht/aesGladman/sha2.cpp \
	irrlicht/aesGladman/fileenc.cpp \
	irrlicht/aesGladman/sha1.cpp \
	irrlicht/aesGladman/hmac.cpp \
	irrlicht/aesGladman/aestab.cpp \
	irrlicht/CImageLoaderDDS.cpp \
	irrlicht/CImageWriterPCX.cpp \
	irrlicht/CGUIComboBox.cpp \
	irrlicht/CBillboardSceneNode.cpp \
	irrlicht/CFileSystem.cpp \
	irrlicht/CParticlePointEmitter.cpp \
	irrlicht/CMountPointReader.cpp \
	irrlicht/CSkyDomeSceneNode.cpp \
	irrlicht/CSceneCollisionManager.cpp \
	irrlicht/CSkinnedMesh.cpp \
	irrlicht/CGUIEnvironment.cpp \
	irrlicht/CTRGouraudAlpha2.cpp \
	irrlicht/CQ3LevelMesh.cpp \
	irrlicht/CD3D9Texture.cpp \
	irrlicht/CMS3DMeshFileLoader.cpp \
	irrlicht/CParticleAnimatedMeshSceneNodeEmitter.cpp \
	irrlicht/CSceneNodeAnimatorRotation.cpp \
	irrlicht/CIrrDeviceFB.cpp \
	irrlicht/COGLES2ParallaxMapRenderer.cpp \
	irrlicht/CSceneNodeAnimatorDelete.cpp \
	irrlicht/CMemoryFile.cpp \
	irrlicht/COBJMeshFileLoader.cpp \
	irrlicht/CParticleFadeOutAffector.cpp \
	irrlicht/irrXML.cpp \
	irrlicht/bzip2/randtable.c \
	irrlicht/bzip2/bzip.css \
	irrlicht/bzip2/bzip2recover.c \
	irrlicht/bzip2/decompress.c \
	irrlicht/bzip2/huffman.c \
	irrlicht/bzip2/bzcompress.c \
	irrlicht/bzip2/crctable.c \
	irrlicht/bzip2/blocksort.c \
	irrlicht/bzip2/bzlib.c \
	irrlicht/IBurningShader.cpp \
	irrlicht/COGLES2FixedPipelineShader.cpp \
	irrlicht/CDefaultSceneNodeAnimatorFactory.cpp \
	irrlicht/CImageLoaderWAL.cpp \
	irrlicht/CDummyTransformationSceneNode.cpp \
	irrlicht/COpenGLShaderMaterialRenderer.cpp \
	irrlicht/CColladaMeshWriter.cpp \
	irrlicht/CParticleCylinderEmitter.cpp \
	irrlicht/CD3D8ParallaxMapRenderer.cpp \
	irrlicht/CXMLWriter.cpp \
	irrlicht/CColorConverter.cpp \
	irrlicht/CSceneManager.cpp \
	irrlicht/CQuake3ShaderSceneNode.cpp \
	irrlicht/CIrrMeshWriter.cpp \
	irrlicht/CFileList.cpp \
	irrlicht/COpenGLDriver.cpp \
	irrlicht/CGUIButton.cpp \
	irrlicht/COSOperator.cpp \
	irrlicht/os.cpp \
	irrlicht/CImage.cpp \
	irrlicht/CParticleAttractionAffector.cpp \
	irrlicht/CGUIContextMenu.cpp \
	irrlicht/CXMLReader.cpp \
	irrlicht/CParticleBoxEmitter.cpp \
	irrlicht/CLimitReadFile.cpp \
	irrlicht/CLogger.cpp \
	irrlicht/COpenGLNormalMapRenderer.cpp \
	irrlicht/CIrrDeviceLinux.cpp \
	irrlicht/CImageLoaderPSD.cpp \
	irrlicht/CGUIToolBar.cpp \
	irrlicht/zlib/crc32.c \
	irrlicht/zlib/compress.c \
	irrlicht/zlib/trees.c \
	irrlicht/zlib/uncompr.c \
	irrlicht/zlib/gzwrite.c \
	irrlicht/zlib/gzclose.c \
	irrlicht/zlib/adler32.c \
	irrlicht/zlib/deflate.c \
	irrlicht/zlib/gzread.c \
	irrlicht/zlib/inflate.c \
	irrlicht/zlib/zutil.c \
	irrlicht/zlib/inffast.c \
	irrlicht/zlib/infback.c \
	irrlicht/zlib/inftrees.c \
	irrlicht/zlib/gzlib.c \
	irrlicht/CTRTextureGouraudVertexAlpha2.cpp \
	irrlicht/CIrrMeshFileLoader.cpp \
	irrlicht/CMeshCache.cpp \
	irrlicht/CTRTextureDetailMap2.cpp \
	irrlicht/CDepthBuffer.cpp \
	irrlicht/CTRTextureLightMapGouraud2_M4.cpp \
	irrlicht/CSceneNodeAnimatorCollisionResponse.cpp \
	irrlicht/CBoneSceneNode.cpp \
	irrlicht/CTRTextureGouraud2.cpp \
	irrlicht/COCTLoader.cpp \
	irrlicht/CImageLoaderPPM.cpp \
	irrlicht/CTRNormalMap.cpp \
	irrlicht/CD3D9NormalMapRenderer.cpp \
	irrlicht/CMY3DMeshFileLoader.cpp \
	irrlicht/CSTLMeshFileLoader.cpp \
	irrlicht/Irrlicht-gcc.cbp \
	irrlicht/CTRTextureGouraudNoZ2.cpp \
	irrlicht/COGLESTexture.cpp \
	irrlicht/CD3D9Driver.cpp \
	irrlicht/CGUICheckBox.cpp \
	irrlicht/COGLESDriver.cpp \
	irrlicht/CIrrDeviceWin32.cpp \
	irrlicht/CSTLMeshWriter.cpp \
	irrlicht/COpenGLExtensionHandler.cpp \
	irrlicht/CTRFlatWire.cpp \
	irrlicht/CIrrDeviceSDL.cpp \
	irrlicht/CParticleMeshEmitter.cpp \
	irrlicht/CTRTextureGouraudNoZ.cpp \
	irrlicht/CTRFlat.cpp \
	irrlicht/CSceneNodeAnimatorCameraFPS.cpp \
	irrlicht/CGUIScrollBar.cpp \
	irrlicht/CSoftwareTexture2.cpp \
	irrlicht/CParticleRingEmitter.cpp \
	irrlicht/CTextSceneNode.cpp \
	irrlicht/CMD2MeshFileLoader.cpp \
	irrlicht/CParticleRotationAffector.cpp \
	irrlicht/CParticleSystemSceneNode.cpp \
	irrlicht/CVideoModeList.cpp \
	irrlicht/CAnimatedMeshHalfLife.cpp \
	irrlicht/CTRTextureGouraudAdd2.cpp \
	irrlicht/CGUIFileOpenDialog.cpp \
	irrlicht/CLMTSMeshFileLoader.cpp \
	irrlicht/CD3D8NormalMapRenderer.cpp \
	irrlicht/CTRTextureGouraud.cpp \
	irrlicht/CD3D9ShaderMaterialRenderer.cpp \
	irrlicht/CGUISpinBox.cpp \
	irrlicht/CD3D9ParallaxMapRenderer.cpp \
	irrlicht/CImageLoaderPCX.cpp \
	irrlicht/CImageLoaderBMP.cpp \
	irrlicht/CD3D8Texture.cpp \
	irrlicht/CSMFMeshFileLoader.cpp
LOCAL_LDLIBS    := -llog -landroid -lEGL -lGLESv1_CM -lGLESv2
LOCAL_CFLAGS := -I./irrlicht/ -I./../include/ -I./include/ -I./irrlicht/libpng/
LOCAL_STATIC_LIBRARIES := android_native_app_glue

include $(BUILD_SHARED_LIBRARY)

$(call import-module,android/native_app_glue)
